version: 2

sources:
  - name: jjsource
    database: edw_source
    schema: jimmy_johns_source
    tables:
      - name: customer
      - name: delivery_address
      - name: employee
      - name: district  
